[package]
name = "auth"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.10.2"
actix-rt = "2.10.0"
jsonwebtoken = "9.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.140"
rand = "0.9.0"
bcrypt = "0.17.0"
futures = "0.3.31"
dotenv = "0.15.0"